Winkellijst_ASP/Models/WinkelLijst.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Winkellijst_ASP.Models
{
    public class WinkelLijst
    {
        public int WinkelLijstId { get; set; }
        public string Naam { get; set; }
        public int GebruikerId { get; set; }
        public Gebruiker Gebruiker { get; set; }
        public DateTime AanmaakDatum { get; set; }
        public List<WinkelLijstProduct> WinkelLijstProducts { get; set; }

    }
}

Winkellijst_ASP/Controllers/AddProductsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Winkellijst_ASP.Areas.Identity.Data;
using Winkellijst_ASP.Data;
using Winkellijst_ASP.Models;
using Winkellijst_ASP.ViewModel;

namespace Winkellijst_ASP.Controllers
{
    [Authorize]
    public class AddProductsController : Controller
    {
        private readonly GebruikerContext _context;
        private readonly UserManager<AppGebruiker> _userManager;

        public AddProductsController(GebruikerContext context, UserManager<AppGebruiker> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private async Task<IActionResult> Main(int id, string q = "")
        {
            WinkelLijst list = await _context.WinkelLijsten.Where(w => w.WinkelLijstId == id).FirstOrDefaultAsync();

            if (list != null)
            {
                var userId = _userManager.GetUserId(User);
                Gebruiker gebruiker = await _context.Gebruikers.FirstOrDefaultAsync(x => x.AppGebruikerId == userId);

                if (gebruiker.GebruikerId != list.GebruikerId)
                {
                    return Forbid();
                }

                var query = _context.Producten.Include(p => p.Afdeling).AsQueryable();

                if (!string.IsNullOrWhiteSpace(q))
                {
                    query = query.Where(p => p.Naam.Contains(q) || p.Afdeling.Naam.Contains(q));
                }

                return View("Index", new AddProductsViewModel
                {
                    List = list,
                    Products = await query.ToListAsync(),
                    WinkelLijstProduct = new WinkelLijstProduct()
                });
            }

            return NotFound();
        }

        // GET: AddProducts/5
        public async Task<IActionResult> Index(int id)
        {
            return await Main(id);
        }

        // GET: AddProducts/5/Search?q=
        public async Task<IActionResult> Search(int id, string q)
        {
            return await Main(id, q);
        }

        // POST: AddProducts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WinkelLijstProductId,Aantal,WinkelLijstId,ProductId")] WinkelLijstProduct winkelLijstProduct)
        {
            if (ModelState.IsValid)
            {
                var winkellijstProduct1 = await _context.WinkelLijstProduct
                    .FirstOrDefaultAsync(wp => wp.ProductId == winkelLijstProduct.ProductId && wp.WinkelLijstId == winkelLijstProduct.WinkelLijstId);

                if (winkellijstProduct1 != null)
                {
                    winkellijstProduct1.Aantal += winkelLijstProduct.Aantal;
                    _context.Update(winkellijstProduct1);
                }
                else
                {
                    _context.Add(winkelLijstProduct);
                }

                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Details", "WinkelLijst", new { id = winkelLijstProduct.WinkelLijstId });
        }
    }
}

Winkellijst_ASP/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Winkellijst_ASP.Data;
using Winkellijst_ASP.Models;
using Winkellijst_ASP.ViewModel;

namespace Winkellijst_ASP.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly GebruikerContext _context;

        public ProductController(GebruikerContext context)
        {
            _context = context;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            SearchProductViewModel searchProductViewModel = new SearchProductViewModel();
            searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling).ToListAsync();
            return View(searchProductViewModel);
        }

        //GET: Searchfilter

        public async Task<IActionResult> Search(SearchProductViewModel searchProductViewModel)
        {
            if (!string.IsNullOrEmpty(searchProductViewModel.ZoekProducten))
            {
                searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling)
                    .Where(c => c.Naam.Contains(searchProductViewModel.ZoekProducten)).ToListAsync();
            }
            else
            {
                searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling).ToListAsync();
            }
            return View("Index", searchProductViewModel);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Product = new Product();
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam");
            return View(productViewModel);
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            Product productNaam = await _context.Producten.FirstOrDefaultAsync(x => x.Naam == productViewModel.Product.Naam);
            if (productNaam != null)
            {
                ModelState.AddModelError(string.Empty, "Deze productnaam bestaat al");
            }
            else if (ModelState.IsValid)
            {
                _context.Add(productViewModel.Product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", productViewModel.Product.AfdelingId);
            return View(productViewModel);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Producten.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Product = product;
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", product.AfdelingId);
            return View(productViewModel);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Product.ProductId)
            {
                return NotFound();
            }
            Product productNaam = await _context.Producten.Where(x => x.Naam == productViewModel.Product.Naam && x.ProductId != id).FirstOrDefaultAsync();
            if (productNaam != null)
            {
                ModelState.AddModelError(string.Empty, "Deze productnaam bestaat al");
            }
            else if (ModelState.IsValid)
            {
                _context.Update(productViewModel.Product);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", productViewModel.Product.AfdelingId);
            return View(productViewModel);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Producten
                .Include(p => p.Afdeling)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Producten.FindAsync(id);
            _context.Producten.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Producten.Any(e => e.ProductId == id);
        }
    }
}

Winkellijst_ASP/Controllers/WinkellijstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Winkellijst_ASP.Areas.Identity.Data;
using Winkellijst_ASP.Data;
using Winkellijst_ASP.Models;
using Winkellijst_ASP.ViewModel;
using Winkellijst_ASP.Helpers;

namespace Winkellijst_ASP.Controllers
{
    [Authorize]
    public class WinkelLijstController : Controller
    {
        private readonly GebruikerContext _context;
        private readonly UserManager<AppGebruiker> _userManager;

        public WinkelLijstController(GebruikerContext context, UserManager<AppGebruiker> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: WinkelLijst
        public async Task<IActionResult> Index()
        {
            try
            {
                var userId = _userManager.GetUserId(User);
                var gebruiker = await _context.Gebruikers.Where(g => g.AppGebruikerId == userId).FirstOrDefaultAsync();

                var list = await _context.WinkelLijsten
                    .Where(w => w.GebruikerId == gebruiker.GebruikerId)
                    .Include(w => w.Gebruiker)
                    .Include(w => w.WinkelLijstProducts)
                    .OrderByDescending(w => w.AanmaakDatum)
                    .ToListAsync();

                return View(list);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        // GET: WinkelLijst/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten
                .Include(w => w.Gebruiker)
                .Include(w => w.WinkelLijstProducts)
                .ThenInclude(winkellijstProduct => winkellijstProduct.Product.Afdeling)
                .FirstOrDefaultAsync(m => m.WinkelLijstId == id);
            if (winkelLijst == null)
            {
                return NotFound();
            }

            return View(winkelLijst);
        }

        // GET: WinkelLijst/Create
        public IActionResult Create()
        {
            WinkellijstCreateViewModel viewModel = new WinkellijstCreateViewModel();
            viewModel.Winkellijst = new WinkelLijst();
            return View(viewModel);
        }

        // POST: WinkelLijst/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WinkellijstCreateViewModel winkellijstCreateViewModel)
        {
            var userId = _userManager.GetUserId(User);
            Gebruiker gebruiker = await _context.Gebruikers.FirstOrDefaultAsync(x => x.AppGebruikerId == userId);
            WinkelLijst winkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.Naam == winkellijstCreateViewModel.Winkellijst.Naam && x.GebruikerId == gebruiker.GebruikerId);
            if (winkelLijst != null)
            {
                ModelState.AddModelError(string.Empty, "De naam voor deze winkellijst bestaat al.");
            }
            if (ModelState.IsValid && gebruiker != null)
            {
                winkellijstCreateViewModel.Winkellijst.GebruikerId = gebruiker.GebruikerId;
                winkellijstCreateViewModel.Winkellijst.AanmaakDatum = DateTime.Now;
                _context.Add(winkellijstCreateViewModel.Winkellijst);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(winkellijstCreateViewModel);
        }

        // GET: WinkelLijst/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten.FindAsync(id);
            if (winkelLijst == null)
            {
                return NotFound();
            }
            WinkellijstEditViewModel winkellijstEditViewModel = new WinkellijstEditViewModel();
            winkellijstEditViewModel.Winkellijst = winkelLijst;
            return View(winkellijstEditViewModel);
        }

        // POST: WinkelLijst/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, WinkellijstEditViewModel winkellijstEditViewModel)
        {
            if (id != winkellijstEditViewModel.Winkellijst.WinkelLijstId)
            {
                return NotFound();
            }
            WinkelLijst controleWinkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.Naam == winkellijstEditViewModel.Winkellijst.Naam && x.GebruikerId == winkellijstEditViewModel.Winkellijst.GebruikerId);
            if (controleWinkelLijst != null )
            {
                ModelState.AddModelError(string.Empty, "De naam voor deze winkellijst bestaat al.");
            }

            if (ModelState.IsValid)
            {
                WinkelLijst winkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.WinkelLijstId == id);
                if (winkelLijst != null)
                {
                    winkelLijst.Naam = winkellijstEditViewModel.Winkellijst.Naam;
                    _context.Update(winkelLijst);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Kon uw winkellijst niet bewerken, probeer later nog eens.");
                }
            }
                    
            return View(winkellijstEditViewModel);
        }

        // GET: WinkelLijst/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten
                .Include(w => w.Gebruiker)
                .FirstOrDefaultAsync(m => m.WinkelLijstId == id);
            if (winkelLijst == null)
            {
                return NotFound();
            }

            return View(winkelLijst);
        }

        // POST: WinkelLijst/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var winkelLijst = await _context.WinkelLijsten.FindAsync(id);
            _context.WinkelLijsten.Remove(winkelLijst);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WinkelLijstExists(int id)
        {
            return _context.WinkelLijsten.Any(e => e.WinkelLijstId == id);
        }
    }
}

Winkellijst_ASP/Views/Winkellijst/Create.cshtml
@model Winkellijst_ASP.ViewModel.WinkellijstCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h2> Maak een nieuwe lijst !</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Winkellijst.Naam" class="control-label"></label>
                <input asp-for="Winkellijst.Naam" class="form-control" />
                <span asp-validation-for="Winkellijst.Naam" class="text-danger"></span>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            </div>
            <div class="form-group">
                <input type="submit" value="Nieuwe Lijst" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p>
    <a class="btn btn-primary" asp-action="Index">Mijn Winkellijsten</a>
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Winkellijst_ASP/Views/Winkellijst/Delete.cshtml
@model Winkellijst_ASP.Models.WinkelLijst

@{
    ViewData["Title"] = "Delete";
}

<h3> Wilt u deze deze lijst verwijderen ?</h3>

<form asp-action="Delete">
    <input type="hidden" asp-for="WinkelLijstId" />
    <div class="form-group">
        <p>Naam: @Html.DisplayFor(modelItem => modelItem.Naam)</p>
    </div>
    <input type="submit" value="Ja" class="btn btn-danger" />
    <button class="btn btn-primary" asp-action="Index">Neen, Terug naar Winkellijst</button>
</form>

Winkellijst_ASP/Views/Winkellijst/Details.cshtml
@model Winkellijst_ASP.Models.WinkelLijst

@using Winkellijst_ASP.Helpers

@{
    ViewData["Title"] = "Details";
}

<h3>Lijst: @Model.Naam</h3>
<hr />

<dl class="row">
    <dt class="col-sm-3">
        Aanmaakdatum:
    </dt>
    <dd class="col">
        @Model.AanmaakDatum.TimeAgo()
    </dd>
</dl>
<a class="btn btn-dark" asp-controller="AddProducts" asp-action="Index" asp-route-id="@Model.WinkelLijstId">+ Producten Toevoegen</a>
<a class="btn btn-primary " asp-action="Index">Terug naar Winkellijstoverzicht</a>
<table class="table mt-4">
    <thead>
        <tr>
            <th>
                Naam
            </th>
            <th>
                Prijs
            </th>
            <th>
                Beschrijving
            </th>
            <th>
                Afdeling
            </th>
            <th>Aantal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (WinkelLijstProduct winkelLijstProduct in Model.WinkelLijstProducts)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => winkelLijstProduct.Product.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => winkelLijstProduct.Product.Prijs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => winkelLijstProduct.Product.Beschrijving)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => winkelLijstProduct.Product.Afdeling.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => winkelLijstProduct.Aantal)
                </td>
            </tr>
        }
    </tbody>
</table>

Winkellijst_ASP/Views/Winkellijst/Edit.cshtml
@model Winkellijst_ASP.ViewModel.WinkellijstEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h3> Bewerk deze winkellijst</h3>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Winkellijst.WinkelLijstId" />
    <div class="form-group">
        <label asp-for="Winkellijst.Naam" class="control-label"></label>
        <input asp-for="Winkellijst.Naam" class="form-control" />
        <span asp-validation-for="Winkellijst.Naam" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Bewaar" class="btn btn-primary" />
        <a class="btn btn-primary" asp-action="Index">Terug naar Winkellijst</a>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Winkellijst_ASP/Views/Winkellijst/Index.cshtml
@model IEnumerable<Winkellijst_ASP.Models.WinkelLijst>

@using Winkellijst_ASP.Helpers

@{
    ViewData["Title"] = "Mijn Winkellijsten";
}

<div class="h2"> Mijn Winkellijsten</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Naam
            </th>
            <th>
                Aanmaakdatum
            </th>
            <th>
                Aantal producten
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.WinkelLijstId">@Html.DisplayFor(modelItem => item.Naam)</a>
                </td>
                <td>
                    @item.AanmaakDatum.TimeAgo()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WinkelLijstProducts.Count)
                </td>
                <td class="text-right">
                    <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.WinkelLijstId"><i class="fas fa-book-open"></i> Bewerk Naam</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.WinkelLijstId"><i class="fas fa-trash-alt"></i> Verwijder</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a class="btn btn-primary" asp-action="Create"> Maak een nieuwe lijst aan !</a>
    <a class="btn btn-secondary" asp-controller="Product">Producten beheren</a>
</p>