Winkellijst_ASP/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Winkellijst_ASP.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string Naam { get; set; }
        public decimal Prijs { get; set; }
        public string Beschrijving { get; set; }
        public int AfdelingId { get; set; }
        public Afdeling Afdeling { get; set; }
        public ICollection<WinkelLijstProduct> WinkelLijstProducts { get; set; }
    }
}

Winkellijst_ASP/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Winkellijst_ASP.Data;
using Winkellijst_ASP.Models;
using Winkellijst_ASP.ViewModel;

namespace Winkellijst_ASP.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly GebruikerContext _context;

        public ProductController(GebruikerContext context)
        {
            _context = context;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            SearchProductViewModel searchProductViewModel = new SearchProductViewModel();
            searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling).ToListAsync();
            return View(searchProductViewModel);
        }

        //GET: Searchfilter

        public async Task<IActionResult> Search(SearchProductViewModel searchProductViewModel)
        {
            if (!string.IsNullOrEmpty(searchProductViewModel.ZoekProducten))
            {
                searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling)
                    .Where(c => c.Naam.Contains(searchProductViewModel.ZoekProducten)).ToListAsync();
            }
            else
            {
                searchProductViewModel.Products = await _context.Producten.Include(p => p.Afdeling).ToListAsync();
            }
            return View("Index", searchProductViewModel);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Product = new Product();
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam");
            return View(productViewModel);
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            Product productNaam = await _context.Producten.FirstOrDefaultAsync(x => x.Naam == productViewModel.Product.Naam);
            if (productNaam != null)
            {
                ModelState.AddModelError(string.Empty, "Deze productnaam bestaat al");
            }
            else if (ModelState.IsValid)
            {
                _context.Add(productViewModel.Product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", productViewModel.Product.AfdelingId);
            return View(productViewModel);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Producten.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Product = product;
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", product.AfdelingId);
            return View(productViewModel);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Product.ProductId)
            {
                return NotFound();
            }
            Product productNaam = await _context.Producten.Where(x => x.Naam == productViewModel.Product.Naam && x.ProductId != id).FirstOrDefaultAsync();
            if (productNaam != null)
            {
                ModelState.AddModelError(string.Empty, "Deze productnaam bestaat al");
            }
            else if (ModelState.IsValid)
            {
                _context.Update(productViewModel.Product);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            productViewModel.Afdeling = new SelectList(_context.Afdelingen, "AfdelingId", "Naam", productViewModel.Product.AfdelingId);
            return View(productViewModel);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Producten
                .Include(p => p.Afdeling)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Producten.FindAsync(id);
            _context.Producten.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Producten.Any(e => e.ProductId == id);
        }
    }
}

Winkellijst_ASP/Controllers/WinkellijstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Winkellijst_ASP.Areas.Identity.Data;
using Winkellijst_ASP.Data;
using Winkellijst_ASP.Models;
using Winkellijst_ASP.ViewModel;
using Winkellijst_ASP.Helpers;

namespace Winkellijst_ASP.Controllers
{
    [Authorize]
    public class WinkelLijstController : Controller
    {
        private readonly GebruikerContext _context;
        private readonly UserManager<AppGebruiker> _userManager;

        public WinkelLijstController(GebruikerContext context, UserManager<AppGebruiker> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: WinkelLijst
        public async Task<IActionResult> Index()
        {
            try
            {
                var userId = _userManager.GetUserId(User);
                var gebruiker = await _context.Gebruikers.Where(g => g.AppGebruikerId == userId).FirstOrDefaultAsync();

                var list = await _context.WinkelLijsten
                    .Where(w => w.GebruikerId == gebruiker.GebruikerId)
                    .Include(w => w.Gebruiker)
                    .Include(w => w.WinkelLijstProducts)
                    .OrderByDescending(w => w.AanmaakDatum)
                    .ToListAsync();

                return View(list);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        // GET: WinkelLijst/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten
                .Include(w => w.Gebruiker)
                .Include(w => w.WinkelLijstProducts)
                .ThenInclude(winkellijstProduct => winkellijstProduct.Product.Afdeling)
                .FirstOrDefaultAsync(m => m.WinkelLijstId == id);
            if (winkelLijst == null)
            {
                return NotFound();
            }

            return View(winkelLijst);
        }

        // GET: WinkelLijst/Create
        public IActionResult Create()
        {
            WinkellijstCreateViewModel viewModel = new WinkellijstCreateViewModel();
            viewModel.Winkellijst = new WinkelLijst();
            return View(viewModel);
        }

        // POST: WinkelLijst/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WinkellijstCreateViewModel winkellijstCreateViewModel)
        {
            var userId = _userManager.GetUserId(User);
            Gebruiker gebruiker = await _context.Gebruikers.FirstOrDefaultAsync(x => x.AppGebruikerId == userId);
            WinkelLijst winkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.Naam == winkellijstCreateViewModel.Winkellijst.Naam && x.GebruikerId == gebruiker.GebruikerId);
            if (winkelLijst != null)
            {
                ModelState.AddModelError(string.Empty, "De naam voor deze winkellijst bestaat al.");
            }
            if (ModelState.IsValid && gebruiker != null)
            {
                winkellijstCreateViewModel.Winkellijst.GebruikerId = gebruiker.GebruikerId;
                winkellijstCreateViewModel.Winkellijst.AanmaakDatum = DateTime.Now;
                _context.Add(winkellijstCreateViewModel.Winkellijst);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(winkellijstCreateViewModel);
        }

        // GET: WinkelLijst/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten.FindAsync(id);
            if (winkelLijst == null)
            {
                return NotFound();
            }
            WinkellijstEditViewModel winkellijstEditViewModel = new WinkellijstEditViewModel();
            winkellijstEditViewModel.Winkellijst = winkelLijst;
            return View(winkellijstEditViewModel);
        }

        // POST: WinkelLijst/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, WinkellijstEditViewModel winkellijstEditViewModel)
        {
            if (id != winkellijstEditViewModel.Winkellijst.WinkelLijstId)
            {
                return NotFound();
            }
            WinkelLijst controleWinkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.Naam == winkellijstEditViewModel.Winkellijst.Naam && x.GebruikerId == winkellijstEditViewModel.Winkellijst.GebruikerId);
            if (controleWinkelLijst != null )
            {
                ModelState.AddModelError(string.Empty, "De naam voor deze winkellijst bestaat al.");
            }

            if (ModelState.IsValid)
            {
                WinkelLijst winkelLijst = await _context.WinkelLijsten.SingleOrDefaultAsync(x => x.WinkelLijstId == id);
                if (winkelLijst != null)
                {
                    winkelLijst.Naam = winkellijstEditViewModel.Winkellijst.Naam;
                    _context.Update(winkelLijst);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Kon uw winkellijst niet bewerken, probeer later nog eens.");
                }
            }
                    
            return View(winkellijstEditViewModel);
        }

        // GET: WinkelLijst/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winkelLijst = await _context.WinkelLijsten
                .Include(w => w.Gebruiker)
                .FirstOrDefaultAsync(m => m.WinkelLijstId == id);
            if (winkelLijst == null)
            {
                return NotFound();
            }

            return View(winkelLijst);
        }

        // POST: WinkelLijst/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var winkelLijst = await _context.WinkelLijsten.FindAsync(id);
            _context.WinkelLijsten.Remove(winkelLijst);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WinkelLijstExists(int id)
        {
            return _context.WinkelLijsten.Any(e => e.WinkelLijstId == id);
        }
    }
}

Winkellijst_ASP/Views/Product/Create.cshtml
@model Winkellijst_ASP.ViewModel.ProductViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Nieuw Product</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.Naam" class="control-label"></label>
                <input asp-for="Product.Naam" class="form-control" />
                <span asp-validation-for="Product.Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Prijs" class="control-label"></label>
                <input asp-for="Product.Prijs" class="form-control" />
                <span asp-validation-for="Product.Prijs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Beschrijving" class="control-label"></label>
                <input asp-for="Product.Beschrijving" class="form-control" />
                <span asp-validation-for="Product.Beschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.AfdelingId" class="control-label"></label>
                <select asp-for="Product.AfdelingId" class="form-control" asp-items="Model.Afdeling"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Nieuw product" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar lijst van producten</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Winkellijst_ASP/Views/Product/Delete.cshtml
@model Winkellijst_ASP.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<p class="text-center">Bent u zeker dat u dit wil verwijderen?</p>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prijs)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prijs)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Beschrijving)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Beschrijving)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Afdeling)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Afdeling.Naam)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Verwijder" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar productlijst</a>
    </form>
</div>

Winkellijst_ASP/Views/Product/Edit.cshtml
@model Winkellijst_ASP.ViewModel.ProductViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Bewerk Product</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Product.ProductId" />
            <div class="form-group">
                <label asp-for="Product.Naam" class="control-label"></label>
                <input asp-for="Product.Naam" class="form-control" />
                <span asp-validation-for="Product.Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Prijs" class="control-label"></label>
                <input asp-for="Product.Prijs" class="form-control" />
                <span asp-validation-for="Product.Prijs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Beschrijving" class="control-label"></label>
                <input asp-for="Product.Beschrijving" class="form-control" />
                <span asp-validation-for="Product.Beschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.AfdelingId" class="control-label"></label>
                <select asp-for="Product.AfdelingId" class="form-control" asp-items="Model.Afdeling"></select>
                <span asp-validation-for="Product.AfdelingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Bewaar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar productlijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Winkellijst_ASP/Views/Product/Index.cshtml
@model Winkellijst_ASP.ViewModel.SearchProductViewModel
@{
    ViewData["Title"] = "Index";
}

<h3>Producten</h3>
<form asp-action="Search" method="get">
    <div class="form-actions no-color">
        <p>
            Zoek een product:
            <input asp-for="ZoekProducten" />
            <input type="submit" value="Zoeken" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-primary">Volledige lijst</a>
        </p>
    </div>
</form>

<div class="row">
    <p>
        <a class="btn btn-dark" asp-action="Create">Voeg een product toe</a>
    </p>
    <p>
        <a class="btn btn-dark ml-2" asp-controller="WinkelLijst" asp-action="Index">Terug naar WinkelLijst</a>
    </p>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Prijs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Beschrijving)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Afdeling)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Product product in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => product.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => product.Prijs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => product.Beschrijving)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => product.Afdeling.Naam)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@product.ProductId">Bewerk</a> |
                    <a asp-action="Delete" asp-route-id="@product.ProductId">Verwijder</a>
                </td>
            </tr>
        }
    </tbody>
</table>